const $ = selector => document.querySelector(selector)
const state = { token: sessionStorage.getItem('zt-ai:admin-token') || '', visitors: [] }
const API_BASE = String(globalThis.ZT_AI_ADMIN_API_BASE || '').replace(/\/$/, '')
const apiUrl = path => `${API_BASE}${path}`
const escapeHtml = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]))
const date = value => value ? new Date(value).toLocaleString() : '—'
async function readJson(response) { const text = await response.text(); try { return JSON.parse(text) } catch { return { error: text } } }
async function request(url, options = {}) { const response = await fetch(apiUrl(url), { ...options, headers: { ...(options.headers || {}), authorization: `Bearer ${state.token}` } }); if (response.status === 401) { logout(); throw new Error('管理员登录已失效') } const body = await readJson(response); if (!response.ok) throw new Error(body.error || '请求失败'); return body }
function showApp() { $('#login-view').classList.add('hidden'); $('#app-view').classList.remove('hidden') }
function showLogin(message = '') { $('#login-view').classList.remove('hidden'); $('#app-view').classList.add('hidden'); $('#login-error').textContent = message }
function logout() { state.token = ''; sessionStorage.removeItem('zt-ai:admin-token'); showLogin() }
function renderOverview(data) { $('#kpi-visitors').textContent = data.visitors; $('#kpi-requests').textContent = data.requests; $('#kpi-tokens').textContent = data.estimatedTokens.toLocaleString(); $('#kpi-cost').textContent = data.estimatedCostUsd == null ? '未配置' : `$${data.estimatedCostUsd.toFixed(4)}`; const products = Object.entries(data.byProduct); const max = Math.max(1, ...products.map(([, value]) => value)); $('#product-chart').innerHTML = products.length ? products.map(([key, value]) => `<div class="bar-row ${key === 'desktop-agent' ? 'agent' : ''}"><span>${key === 'web' ? '公开网页' : '桌面 Agent'}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.round(value / max * 100)}%"></div></div><strong>${value}</strong></div>`).join('') : '<div class="empty">还没有调用记录</div>'; const models = Object.entries(data.byModel); $('#model-list').innerHTML = models.length ? models.map(([key, value]) => `<div class="model-row"><strong>${escapeHtml(key)}</strong><span>${value} 次调用</span></div>`).join('') : '<div class="empty">还没有模型调用</div>' }
function renderVisitors(items) { state.visitors = items; $('#visitor-table').innerHTML = items.length ? items.map(item => `<tr data-id="${escapeHtml(item.id)}"><td><strong>${escapeHtml(item.visitorId)}</strong><br><small>${escapeHtml(item.id)}</small></td><td><span class="product-tag">${item.product === 'web' ? '公开网页' : '桌面 Agent'}</span></td><td>${escapeHtml(item.maskedIp)}</td><td>${item.requestCount}</td><td>${(item.models || []).map(escapeHtml).join(' · ')}</td><td>${date(item.lastSeenAt)}</td><td><button class="row-action" data-detail="${escapeHtml(item.id)}">查看 ↗</button></td></tr>`).join('') : '<tr><td colspan="7" class="empty">暂无匹配访客</td></tr>'; document.querySelectorAll('[data-detail]').forEach(button => button.addEventListener('click', () => openDetail(button.dataset.detail))) }
async function openDetail(id) { try { const detail = await request(`/api/admin/visitors/${encodeURIComponent(id)}`); $('#detail-title').textContent = detail.visitor.visitorId; const usage = detail.usage || []; $('#detail-content').innerHTML = `<div class="detail-grid"><div><span>产品</span><strong>${escapeHtml(detail.visitor.product)}</strong></div><div><span>完整 IP</span><strong>${escapeHtml(detail.visitor.lastIp)}</strong></div><div><span>首次访问</span><strong>${date(detail.visitor.firstSeenAt)}</strong></div><div><span>最近访问</span><strong>${date(detail.visitor.lastSeenAt)}</strong></div></div><div class="drawer-section"><h3>调用审计 · ${usage.length} 次</h3>${usage.length ? usage.map(item => `<div class="usage-card"><span>${date(item.createdAt)} · ${escapeHtml(item.requestType)} · ${escapeHtml(item.status)}</span><strong>${escapeHtml(item.model)} · ≈ ${item.estimatedTotalTokens} tokens${item.estimatedCostUsd == null ? '' : ` · $${item.estimatedCostUsd}`}</strong></div>`).join('') : '<div class="empty">暂无调用</div>'}</div><div class="drawer-section"><h3>消息时间线</h3>${detail.messages.length ? detail.messages.map(item => `<div class="message ${item.role === 'assistant' ? 'assistant' : ''}"><small>${item.role === 'assistant' ? 'ZT.AI' : '访客'} · ${date(item.createdAt)}</small>${escapeHtml(item.content)}</div>`).join('') : '<div class="empty">暂无消息内容</div>'}</div>`; $('#detail-drawer').classList.remove('hidden') } catch (error) { alert(error.message) } }
async function load() { try { const [overview, visitors] = await Promise.all([request('/api/admin/overview'), request('/api/admin/visitors')]); renderOverview(overview); renderVisitors(visitors); $('#last-sync').textContent = `同步于 ${new Date().toLocaleTimeString()}` } catch (error) { if (state.token) $('#login-error').textContent = error.message } }
$('#login-form').addEventListener('submit', async event => { event.preventDefault(); const button = event.currentTarget.querySelector('button'); button.disabled = true; $('#login-error').textContent = ''; try { const body = await readJson(await fetch(apiUrl('/api/admin/login'), { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ password: $('#admin-password').value }) })); if (!body.token) throw new Error(body.error || '管理员登录失败'); state.token = body.token; sessionStorage.setItem('zt-ai:admin-token', state.token); $('#admin-password').value = ''; showApp(); await load() } catch (error) { $('#login-error').textContent = error.message } finally { button.disabled = false } })
$('#logout').addEventListener('click', async () => { await fetch(apiUrl('/api/admin/logout'), { method: 'POST', headers: { authorization: `Bearer ${state.token}` } }).catch(() => {}); logout() }); $('#refresh').addEventListener('click', load); $('#drawer-close').addEventListener('click', () => $('#detail-drawer').classList.add('hidden')); $('#drawer-x').addEventListener('click', () => $('#detail-drawer').classList.add('hidden')); $('#product-filter').addEventListener('change', async event => { renderVisitors(await request(`/api/admin/visitors?product=${encodeURIComponent(event.target.value)}`)) }); let queryTimer; $('#visitor-query').addEventListener('input', event => { clearTimeout(queryTimer); queryTimer = setTimeout(async () => renderVisitors(await request(`/api/admin/visitors?q=${encodeURIComponent(event.target.value)}`)), 250) }); if (state.token) { showApp(); load() }
